// Auto-generated by scripts/generate-typechain.mjs. Do not edit manually.
import type { Abi } from "viem";
import swap2pArtifact from "../app/lib/swap2p/generated/Swap2p.json";

export const swap2pAbi = swap2pArtifact.abi as Abi;
